### ISSUE TITLE
Weird characters on side bar

### ISSUE THREAD

**Issue by laullon** [Uncommon/Xit#273]
![screen shot 2017-04-19 at 17 23 17](https://cloud.githubusercontent.com/assets/79835/25188001/ed9aa734-2524-11e7-818a-a4cf5400185c.png)

**Comment by Uncommon** [comment]
How many remotes are there actually? Just origin?

**Comment by laullon** [comment]
Yes, just Origin.

**Comment by Uncommon** [comment]
Weird. How did the repository get into that state? Cloned from GitHub?

**Comment by laullon** [comment]
cloned from a private git repo

**Comment by Uncommon** [comment]
It looks like the problem is that `toStringArray()` in XTRepository.swift assumes that the list of strings is null-terminated, and it should be checking the count instead. I'll make that change and let you try it out since I can't replicate the problem myself.

**Comment by Uncommon** [comment]
That should do it (e98e0130372c3dae3ba65b0db7f590eba8c843dc). Can you try building from the latest master branch? Or should I send you a binary?

**Comment by laullon** [comment]
will try to build it... but send me the binary just in case.

Germán Laullón
