### ISSUE TITLE
Build issues, /usr/local/lib/libssh2.a is AWOL again

### ISSUE THREAD

**Issue by JanX2** [Uncommon/Xit#336]
Just tried to build Xit. A simple clone of HEAD (3df4178d155c49ff9cdb568f75be587aa27b6c0c). Then a `git submodule update --init --recursive`. 

I’m getting two issues when building for profiling:

> clang: error: no such file or directory: '/usr/local/lib/libssh2.a'

'Xit/objective-git/External/libssh2' is available so I don’t see why '/usr/local/lib/libssh2.a' needs to exist.

Additionally, I get this:

> Xit/objective-git/ObjectiveGit/GTObjectDatabase.m:28:9: 'NSError+Git.h' file not found

**Comment by Uncommon** [comment]
Can you build Objective Git at head?

**Comment by JanX2** [comment]
No. Same error:

> clang: error: no such file or directory: '/usr/local/lib/libssh2.a'

**Comment by Uncommon** [comment]
That file exists on my system. Did you run the Objective Git bootstrap script?

**Comment by JanX2** [comment]
So `script/update_libgit2`doesn’t do that? Maybe that is something that could be fixed upstream to allow building OOTB?

**Comment by Uncommon** [comment]
You do have to run the `bootstrap` script to get everything set up for libgit2 and Objective Git. This is mentioned in the CONTRIBUTING.md file.

I'm working on removing the dependency on Objective Git (#332), but to some degree I will still have to replicate what that script does.

**Comment by JanX2** [comment]
After bootstrapping, Xit builds using Xcode 9.2 on 10.12.6.

**Comment by peterwillcn** [comment]
https://github.com/gitx/gitx/issues/405
