### ISSUE TITLE
GitLab service support

### ISSUE THREAD

**Issue by verlanmar** [Uncommon/Xit#346]
It would be nice to have support for GitLab.
Thanks!

**Comment by Uncommon** [comment]
What specific features would you like to see?

**Comment by verlanmar** [comment]
Hi!
Just the ability to authenticate via GitLab's personal access token.
Thanks!

**Comment by Uncommon** [comment]
Authenticating just for basic operations like pushing and pulling?

**Comment by verlanmar** [comment]
Yes, just so you can do some regular work without having to use / setup SSH.

**Comment by Uncommon** [comment]
Done in e0d14e99ca4e877503266eddaac855694f5ddc9d
