### ISSUE TITLE
Add width markers in commit message area

### ISSUE THREAD

**Issue by barijaona** [Uncommon/Xit#425]
It is often [recommended](https://chris.beams.io/posts/git-commit/ "How to Write a Git Commit Message") that :
- subject line in commit messages do not exceed 50 characters
- body text in commit messages are wrapped to 72 characters

It would be great to include visual cues (fine dotted lines ?) for these widths.

**Comment by Uncommon** [comment]
So an indicator on the first line, and another one for the remaining lines? I think we'd want to have a setting at the app level, and also be able to override it in each repository because projects will have different practices.

**Comment by barijaona** [comment]
GitX and GitUp just display two small grey lines at 50 and 72. This appears reasonable to me, as these are only cues.

Some people have [marks as comments in their commit template](https://gist.github.com/adeekshith/cd4c95a064977cdc6c50). This is more flexible.
But currently, commit templates are not really convenient in Xit, as comments must be removed manually.

**Comment by Uncommon** [comment]
Yes, comments should be filtered out. Filed as #426.
