### ISSUE TITLE
CLI Launcher / Command Line Helper

### ISSUE THREAD

**Issue by pshirshov** [Uncommon/Xit#428]
Hi,,

It would be great to have a way to launch Xit in current directory from terminal.

Latest GitX fork does support that.

The easiest way would be to parse app args, so the user may invoke it like

```
open /Applications/Xit.app --args `pwd`
```

**Comment by Uncommon** [comment]
Is there anything you would like it to be able to do besides open a specified directory?

**Comment by pshirshov** [comment]
Nope

**Comment by Uncommon** [comment]
Would `open -a Xit <path>` work well enough for your purposes?

**Comment by pshirshov** [comment]
Yeah, it would be great!

**Comment by Uncommon** [comment]
Alright, since that works and it's easy, I'll go ahead and close this. Implementing a proper command line interface doesn't seem worthwhile since `open` does what is needed.
