### ISSUE TITLE
A Column for branches tags, and for commit hash

### ISSUE THREAD

**Issue by varijkapil13** [Uncommon/Xit#442]
Somewhat similar to what GitKraken has.

Working with multiple branches and tags at the same time, makes it tedious to locate the branches and tags when they are merged together with the commit messages. Although they have different styling than the commit but having them in a different column would allow the app to show different statuses more clearly, for example -> when `master` and `origin/master` are actually synced together it could be shown with a combination of icons, instead of writing both branch names on the same level, saving space for the commit message.

Similarly with commit hash it would be a nice feature to show the shortened commit hash too. Since then you can read the commit hash directly and correlate it somewhere. (GitHub and GitLab fr example, always write the shortened commit hash next to the commits.)

**Comment by Uncommon** [comment]
I just added the commit hash column a couple of days ago 😁

**Comment by Uncommon** [comment]
I think putting branch/tag names in a separate column should be a preference... maybe add it to the columns menu, so if that column is showing then they appear there, otherwise they're combined with the commit summary like they are now.

**Comment by varijkapil13** [comment]
> I just added the commit hash column a couple of days ago 😁

Oh, I just pulled changes to my fork. Sorry my bad! :)

> I think putting branch/tag names in a separate column should be a preference... maybe add it to the columns menu, so if that column is showing then they appear there, otherwise they're combined with the commit summary like they are now.

Seems like a good idea to me. I will get on with it

**Comment by varijkapil13** [comment]
Okay I have working version of this, but it does not quite justify what I was suggesting. 

Maybe a better solution would be showing the branch names before the git-graph, rather than a different column. Different column makes it look detached from the whole history. 
I will try to make a version where it is rendered in the same cell, but in this order

`branch-graph-commitMessage`.

The user should be able to switch between this in app preferences, since the columns menu would be wrong place for this preference.

Also, I am an iOS developer trying to enter the world of Mac Development, please bear with me the silly mistakes or slow development :)

**Comment by Uncommon** [comment]
Sounds good so far. I look forward to checking it out when you're ready.

**Comment by Uncommon** [comment]
Just checking in - @varijkapil13 are you still planning to do this?

**Comment by varijkapil13** [comment]
I was working on the tags column but after a lot of tries it was not turning out in a way that would make the information easier to parse, also I was struggling with the design.

But then I couldn’t continue this. I am sorry should have updated here earlier. I just lost track of things.

On 21. Sep 2020, at 17:42, David Catmull <notifications@github.com> wrote:

﻿

Just checking in - @varijkapil13<https://github.com/varijkapil13> are you still planning to do this?

**Comment by Uncommon** [comment]
OK, thanks. I'll see if I can come up with a way to make it work.

**Comment by Uncommon** [comment]
Refs column added in 832397559d61b7a7746c44f64c1e360cdceb11ff
