### ISSUE TITLE
Homebrew, M1

### ISSUE THREAD

**Issue by JanX2** [Uncommon/Xit#482]
I ran into a few issues trying to build Xit natively for Apple silicon. Most of these were, because the default homebrew root changed from "/usr/local" to "/opt/homebrew". I also had to change the architecture to ARCHS_STANDARD. 

If I had achieved a universal binary build, I would just have opened a pull request. But the libgit2 script makes it necessary to build two separate "libgit2.a" for aarch64 and x86_64 and merge them. At least unless there is a better solution. 

Here is my hacked branch:
https://github.com/janx2/Xit/tree/M1

**Comment by JanX2** [comment]
Any thoughts @Uncommon?

**Comment by JanX2** [comment]
I can test any changes you make. :)

**Comment by Uncommon** [comment]
I finally got myself a new laptop, so I'm working on this now. I just got it working for ARM; Next I'll make sure it works both ways.

**Comment by Uncommon** [comment]
I've made some changes which I believe enable building for ARM without breaking the Intel build. A universal build will be more challenging because it requires universal builds of libgit2 as well as the libraries it uses.

In the process I've also changed the primary branch from `master` to `main`.
