### ISSUE TITLE
Issue with libgit on Apple Silicon 

### ISSUE THREAD

**Issue by richy486** [Uncommon/Xit#508]
on a M2 mac with macOS 14.6.1 with Xcode 15.4

getting the warnings such as:
```
ld: warning: ignoring file '[path to]/Xit/libgit2-mac.a[180](crypt_commoncrypto.c.o)': found architecture 'x86_64', required architecture 'arm64'
```
for a bunch of the .o files.

and the errors such as:
```
Undefined symbol: _git_annotated_commit_free
```
for a bunch of the `_git_*` symbols.

I've reinstalled libgit2 via brew and "My Mac" is the only option to build with.

**Comment by Uncommon** [comment]
I've been running on an M2 MacBook Air and an M1 MacBook Pro for a while with no issues. You shouldn't need to install libgit2 with Homebrew since it's a submobule. Is the libgit2 target compiling successfully?

**Comment by richy486** [comment]
So I had Homebrew set to the old path `/usr/local` instead of the new path `/opt/homebrew` because this M2 mac was migrated from an Intel mac, I reinstalled Homebrew with [this guide](https://medium.com/@ravi.mba.techie/a-minimalist-guide-to-migrate-homebrew-from-intel-macs-to-apple-silicon-macs-in-a-simple-5-steps-3e545576dab5) and built again but libssh was still being referenced from `/usr/local` so I swapped the order of the `LIBRARY_SEARCH_PATHS` in the project folder so `/opt/homebrew/lib` comes first and it built.

**Comment by Uncommon** [comment]
Great, glad you got it working. That Homebrew path change for M1/M2 is a pain sometimes.

**Comment by richy486** [comment]
Yeah glad it works, just made a small PR with the order change in the project: https://github.com/Uncommon/Xit/pull/509
